let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')

	source ~/.vim/common-plugins.vim

	" Nvim already uses vim-sensible
	Plug 'tpope/vim-sensible'
	Plug 'ghifarit53/tokyonight-vim'

call plug#end()

" Tokyonight stuff
set termguicolors
let g:tokyonight_enable_italic = 1
let g:tokyonight_style = "night"
let g:lightline = {'colorscheme' : 'tokyonight'}
colorscheme tokyonight

source ~/.vim/vim.d/**/*.vim
